### ISSUE TITLE
Call to undefined function AbraFlexi\_()

### ISSUE THREAD

**Issue by Pepiik** [Spoje-NET/php-abraflexi#10]
Hello

After calling function  ObjednavkaPrijata i got this error

```
$config = [
  'company' => 'firma',
  'url' => 'http://192.168.100.16:5434',
  'user' => 'test',
  'password' => '',
];
$init = 'code:OBP0002/2021';
$order = new ObjednavkaPrijata($init, $config);
```

 `Call to undefined function AbraFlexi\_()`

![image](https://user-images.githubusercontent.com/28764197/112844883-82e4c880-90a4-11eb-8820-864c18c562e3.png)

spojenet/flexibee : 2.4
php: 8.0

Thanks

**Comment by Vitexus** [comment]
Hallo @Pepiik  , please us the **gettext** module for php which contains **_()** command.
Or put the 

```php
if(!function_exists('_')){ 
 function _($x){ return $x;  }
}
```
If you do not use Gettext localization
