### ISSUE TITLE
Metoda performRequest z urlSuffix null zlyha

### ISSUE THREAD

**Issue by Matej-ch** [Spoje-NET/php-abraflexi#11]
Pokusal som sa vykonat akciu nad fakturov `$invoice->performAction('storno','int')`

Akcia zlyha pretože `AbraFlexi\RO::performRequest()`  požaduje string, ale metoda `AbraFlexi\RW::performAction` ju vola z null

U seba som to vyriesil tým že som null prepísal na prázdny string. Niesom si istý či ide o korektné riešenie.

**Comment by Vitexus** [comment]
Dobrý den, děkuji za upozornění.  
Knihovnu teprve postupně adaptuji na strict types a PHP8, takže tam ještě leckde na méně často používaných místech zůstávají problémy. Tento jeden pro vás rád opravím.
Prosím vyčkejte update.

**Comment by Vitexus** [comment]
Opraveno.
