### ISSUE TITLE
v2 - Production ready

### ISSUE THREAD

**Issue by vasikgreif** [Spoje-NET/php-abraflexi#12]
Dobrý den,
v první řadě moc díky za práci na knihovně! Rád bych se zeptal, jestli je v2 vhodá pro použití na produkci - chystám se psát novou integraci na Flexibee, a rád bych už využil novou verzi.

Díky!

**Comment by Vitexus** [comment]
Dobrý den, 
děkuji za uznání. Vyvíjím na základě požadavků na produkci. Co se týče použití bych viděl dva rozdíly: 
Zmizely třídy: FlexiBeeRO a FlexiBeeRW a data čtená z flexibee jsou v rámci možností typovaná.
Typování výsledků je však možné vypnout v parametrech konstruktoru.

**Comment by Vitexus** [comment]
Když už se ptáte, sepsal jsem něco dokumentace a mimo jiné i poznámky k migraci:

https://github.com/Spoje-NET/php-abraflexi/commit/2205a304a01360d45c789fa95ad2cb1188a7c752

V tento okamžik mě trápí hlavně prozkoušení aktuálního stavu. Konečně jsem se rozhoupal a zapnul vyhazování vyjímek a teď jen čekám kde se nějaká objeví abych jí případně pořešil. 

Určitě ocením zpětnou vazbu. Pokud by jste mohl pokusně v nějakém svém stávajícím projektu použít verzi 2.0 a napsat mi jak to dopadlo bylo by to super.  Knihovnu jsem už zkoušel např v prostředí nette apod. ale většinou jí provozuji ve svém vlastním prostředí založeném na EaseCore  tudíž nevím jak by se cokoliv mohlo chovat u jiného vendora.

**Comment by vasikgreif** [comment]
Díky, mohl byste prosím upravit composer, aby šlo knihovnu nainstalovat? `composer require spojenet/abraflexi` nefunguje.

**Comment by Vitexus** [comment]
Ja jsem o tom uvazoval ale prejmenovat projekt neni uplne snadne. 
Udelám to tak že hlavní branch nebude stávající master ale nová 2.0

**Comment by Vitexus** [comment]
> Díky, mohl byste prosím upravit composer, aby šlo knihovnu nainstalovat? `composer require spojenet/abraflexi` nefunguje.


Já to zatím používám jako **dev-abraflexi**

Viz např.


```json
{
    "name": "vitexsoftware/abraflexi-digest",
    "description": "Periodical AbraFlexi digest.",
    "version": "dev-main",
    "authors": [
        {
            "name": "Vitex",
            "email": "info@vitexsoftware.cz"
        }
    ],
    "minimum-stability": "dev",
    "type": "project",
    "require": {
        "vitexsoftware/ease-twbootstrap4-widgets-flexibee": "* 9999999-dev",
        "vitexsoftware/ease-twbootstrap4-widgets": ">=1.3",
        "vitexsoftware/flexibee-bricks": "* dev-abraflexi"
    },
    "autoload": {
        "psr-4": {
            "AbraFlexi\\Digest\\": "src/Digest/"
        }
    }
}

```

Hlavně díky vám jsem se rozhoupal a pracuji na release, ktery jiste prijde v blízké době.

**Comment by vasikgreif** [comment]
Díky, také jsem to tak zatím udělal.:-)

**Comment by Vitexus** [comment]
Dal bych tomu tak +- týden, Pokud nenajdu nějaký zásadní problém, tak to nakonec přehodím.

**Comment by vasikgreif** [comment]
Super, moc díky. Určitě dám vědět, jak se mi knihovna používá.

**Comment by Vitexus** [comment]
Tak zatím pomaličku: https://github.com/Spoje-NET/php-abraflexi/releases/tag/2.8

**Comment by vasikgreif** [comment]
Super, díky!
