### ISSUE TITLE
Podpora výstupů v PL a RU

### ISSUE THREAD

**Issue by thomasdv** [Spoje-NET/php-abraflexi#15]
Dobrý den,

v knihovně chybí podpora PL a RU tiskových výstupů. Flexi to podle všeho reálně umí, jen to chybí v dokumentaci. Bylo by možné doplnit?

Viz https://demo.flexibee.eu/c/demo/faktura-vydana/1.pdf?report-lang=pl

Děkuji.

**Comment by Vitexus** [comment]
Dobrý den, 
můžete být prosím trochu konkrétnější ? Mám za to že volba jazyka pro tisk není nikde žádným způsobem omezena. 
Případně mi pošlete kousek kódu, jak si představujete že by se to mělo volat.

Já v zásadě nemám moc možnost zjistit jaké všechny jsou v daný okamžik k dispozici a tak volání požadovaného jazyka nijak nekontroluji ani neomezuji. viz.: https://github.com/Spoje-NET/php-abraflexi/blob/2.0/src/AbraFlexi/RO.php#L2485

Děkuji za Vaši pomoc při zlepšování knihovny

**Comment by thomasdv** [comment]
Dobrý den,

děkuji za bleskovou reakci. 

Rád bych 2.0 nasadil do produkce, zatím na ní testujeme a je to bez problémů. Budete pro ni průběžně vydávat nějaké releasy, např. s touto změnou? Nejsou asi jasné instrukce ohledně názvu knihovny pro composer. Aktuálně stahuji přes "spojenet/flexibee": "^2.0", je to správně?

**Comment by Vitexus** [comment]
Ano, přechod na novou generaci knihovny řeším zde: https://github.com/Spoje-NET/php-abraflexi/issues/12
