### ISSUE TITLE
Incorrect logic values parsing

### ISSUE THREAD

**Issue by petaak** [Spoje-NET/php-abraflexi#20]
https://github.com/Spoje-NET/php-abraflexi/blob/2.0/src/AbraFlexi/RO.php#L1018

boolval('true') is `true` but boolval('false') is also `true`, therefore all the logic values are transformed to `true`

**Comment by thomasdv** [comment]
Dobrý den,

na tuto chybu jsme také narazili a je to docela problém. Bylo by možné u takto zásadních fixů udělat release? Nebo jakým způsobem je možné natáhnout opravenou verzi?

Díky moc.

**Comment by Vitexus** [comment]
Dobrý den @thomasdv  , 
na release právě pracuji.  Prosím vydržte ještě chvíli.
Děkuji za pochopení
