### ISSUE TITLE
Problém se zpracováním datumů.

### ISSUE THREAD

**Issue by thomasdv** [Spoje-NET/php-abraflexi#25]
Dobrý den, pokud udělám jednoduchou operaci:

```
$inv = new FakturaVydana($invoiceId);
$inv->takeData(["stavMailK" => "stavMail.odeslano"]);
$inv->sync();
```

Dostávám chybovou hlášku:
```
'message' => 'Zadaný text 'null' musí být datum'
'for' => 'eetDatCasTrzby'
'path' => 'faktura-vydana[id=539].eetDatCasTrzby'
'value' => 'null'
'code' => 'PROP'
```

Přitom se s tím údajem vůbec nepracuje. Asi by bylo dobré v entitě faktury kontrolovat textový "null" u datumu a případně opravdu nastavit na null?

**Comment by thomasdv** [comment]
Zároveň s tím souvisí i následující:

```
Error: 
Method AbraFlexi\Date::__toString() must return a string value
```

**Comment by Vitexus** [comment]
Tam je hodně zabojováno, ale asi jste našel chybyičku. Děkuji za bugreport. Pořeším to to obratem.

**Comment by Vitexus** [comment]
@thomasdv  Vámi daný příklad bych zapsal úsporněji:

```php
$inv = new FakturaVydana($invoiceId,['autoload'=>false]);
$inv->setDataValue("stavMailK" , "stavMail.odeslano");
$inv->saveToAbraFlexi();
```

Ale to samozřejmě neznamená že by vámi vrácený příkald měl končit chybou.

**Comment by Vitexus** [comment]
@thomasdv  zkuste to prosím s poslední aktualizací v mainu. Pokud vám bude šplapat všechno dobře, tak bych uďál release.

**Comment by thomasdv** [comment]
@Vitexus, díky main je nyní bez chyby.

**Comment by thomasdv** [comment]
@Vitexus, mimochodem zkouším vámi doporučený úspornější kód, ale ten také bohužel končí chybou. 

```php
$inv = new FakturaVydana(531, ['autoload'=>false]);
```

```php
File: .../spojenet/flexibee/src/AbraFlexi/RO.php:628

TypeError
preg_match() expects parameter 2 to be string, int given
```

ID faktury (integer) neprojde podmínkami v processInit když je autoload nastavený na false.

Podmínka v `RO.php:628` by imho měla kontrolovat, jestli je `$init` string.
