### ISSUE TITLE
Chybí evidence Sklad

### ISSUE THREAD

**Issue by RAD-X** [Spoje-NET/php-abraflexi#30]
Zdar,
chybí evidence Sklad. Má to nějaký důvod, nebo jsem jen něco přehlédl? :-)
Jinak díky APInu - už ji nějakých pár let používáme na zjednodušení přesunu zboží ze skladu. Sice je to jen prachsprostý zlomek využitelnosti API... ale teď při rozšiřování funkčnosti jsem všiml tohoto problému.

**Comment by Vitexus** [comment]
Zdravim, zatim to po mě nikdo nechtěl. Ono to ani nemá moc smysl, pokud do toho objektu nepřilepim ještě něco (jako třeba do banky je přidana funkce na stažení výpisů)

Každý další objekt znamená macatější dokumentaci a nutnost myslet na nej při testech, takže pokud na nějakou evidenci vyloženě nepotřebuju dělat classu tak ji nedělám.

vlastní objekt skladu si můžete udělat takto:

```php
$store = new RW('code:HLAVNI_SKLAD',['evidence'=>'sklad']);
```

nebo i s definicí třídy:


```php
    <?php
    /**
     * @link https://demo.abraflexi.eu/c/demo/sklad/properties Vlastnosti evidence
     */
    class Sklad extends /AbraFlexi/AbraFlexi/RW
    {
        /**
         * Evidence užitá objektem.
         *
         * @var string
         */
        public $evidence = 'sklad';
    }
```

p.s. Díky za bugreport. Potšilo ...

**Comment by RAD-X** [comment]
Dík za zpětnou odezvu. Hned po mém včerejším příspěvku jsem si udělal soubor s novou definicí třídy.
Ale Tvůj inline návrh tvoření vlastního objektu skladu mi přijde univerzálnější, takže si to asi ještě upravím.  :-)

**Comment by Vitexus** [comment]
Dobrá tedy, nechme to zatím tak. 
Nicméně nebráním se případným pull requestum a zůstávám s pozdravem.
