### ISSUE TITLE
Označení usera při konfiguraci

### ISSUE THREAD

**Issue by michaeldojcar** [Spoje-NET/php-abraflexi#32]
Ahoj, díky moc za knihovnu, která nám brutálně usnadňuje práci.

Malý dotaz nebo podnět:
v nastavení konfigurace pomocí konstant je user označován jako ABRAFLEXI_LOGIN, ale při nastavení proměnných rovnou pomocí instance třídy je označený jako _user_. Je tato drobná odlišnost úmysl?

**Comment by Vitexus** [comment]
Dobrý den,
je to opravdu záměr.
Konfigurační klíče velkými písmeny byly dodány až dodatečně. Púvodně se všechno nastavovalo pouze malými protože se více podobají proměnným.

Důvodem je historický vývoj kdy aplikace pro kterou byla knihovna psána, měla .php konfigurák kde připojení bylo definováno jako asociativní pole.
O pár let později jsem usoudil že je to bezpečnostní díra a milý konfigurák změnil svoji koncovku na json.

Takto to několik dalších let stačilo, než přišla kontejnerizace. S potřebou mít hotový image kterému se před spuštěním jenom nastaví proměnné prostředí přišel aktuální způsob zavádění konfigurace.

Původně jsem uvažoval udělat jenom statickou konverzní funkci, ale když se pak ukázalo že jí volám ve 100% případů, byla "rozpuštěna" do initu třídy.

Jak to používáme nyní je dobře vidět např. zde: https://github.com/VitexSoftware/abraflexi-raiffeisenbank/blob/28a6a3a7dc9fe60960695f7eea17351e36637c6b/src/setup.php#L16



ps.
díky za vaše uznání, potěšilo.

**Comment by michaeldojcar** [comment]
Jasně, šlo mi hlavně o to názvosloví, že jednou je to login a jednou user.

**Comment by Vitexus** [comment]
No být vámi, tak nesměřuji díky na mě ale do https://github.com/dativery a hlavně asi na https://github.com/fersman za to jak krásně pojmenovali endpointy agend/evidencí v té nejčistější Czechlish :laughing: takže jsem ten galimatiáš mohl po jejich vzoru rozvinout.

Ale teď vlastně nevím co s tím. Jeno přejmenovat (tak či onak) to nemohu tím bych porušil zpětnou kompatibilitu a jistotu že mě někdo zakový akt neukamenuje.

Mohl bych vzít v potaz oba možné tvary, ale to se mi taky nechce protože jsou řešeny na dost exponovaném místě (prakticky v konstruktoru) takže každé IF které tam přidám se vykonává mnohatisíckrát a já bych rád taková místa spíše redukoval. 

Pokud bych měl k takové úpravě přistoupit vážně a init třídy prohnat profilerem a pak ještě jednou s tím jedním IF navíc. Pokud by zafungovaly optimalizace PHP a dopad na výkon by byl mizivý tak bych mohl brát v potaz více tvarů konfiguračního klíče pro jméno účtu přihlašujícího k API ...

( Bych nejraději na takovouhle věc udělal anketu, ale to asi github neumí ... )
