### ISSUE TITLE
Dry-run a sync

### ISSUE THREAD

**Issue by Pepino483** [Spoje-NET/php-abraflexi#33]
Když při testování nastavím `dry-run` a pro uložení záznamu použiju `sync` tak funkce vždy vrátí `false` což podle mě není ideální chování. Navrhuji upravit funkci `sync` aby brala v potaz jestli je `dry-run` nastavený nebo ne.

**Comment by Vitexus** [comment]
S ostudou se přiznám, že DryRun nepoužívám a tak jsem jeho podporu do knihovny moc nezavedl. Rád si od Vás v této věci nechám poradit. Zatím tedy malé shrnutí:

>> Funkce `RW::sync()` vrací true pokud se záznam úspěšně uloží a načte.

**Je proto třeba pamatovat i na vytvoření nového záznamu, který v dry režimu nevznikne a tudíž následné čtení vrátí 404 ...**

Budu to muset prokrokovat jak se to vlastně teďka přesně chová. Většinou se snažím v knihovně kopírovat chování API, i když to třeba přinese potíže (jako v případě zrušení defaultního ?limit=0 blahé paměti). 

Sync bych zatím tedy neměnil a zaměřil bych se na to, co v dry režimu vrátí uložení záznamu.

**Comment by Pepino483** [comment]
Jde o to, že v celé aplikaci používáme pro ukládání záznamů funkci sync. Při použití dry-run api flexi vrací totožný záznam jako bez použití dry-run ale je jasné, že se ho již nepodaří načíst protože neexistuje.

Nyní, když přidáváme nějakou funkčnost k existujícímu kódu tak musíme krom přidání dry-run ještě upravovat i uložení záznamu (změna funkce sync např na inserttoabraflexi, nebo jinak) protože funkce sync najednou nevrací to, co je požadováno.

Proto je z mého pohledu žádoucí funkci sync upravit tak, aby při použití dry-run již neprováděla načtení záznamu z abry a pouze při návratovém kódu 200 vrátila “uložený” záznam.

**Comment by Vitexus** [comment]
Dobrá tedy. Zkusím něco spíchnout.

**Comment by Vitexus** [comment]
A safra já to zformátoval ... takže v podstatě se změnilo toto:


Sync v DryRun módu neprovede následné čtení ale je spokojen když mu zápis vráti 200

```php
    /**
     * Insert current data into AbraFlexi and load actual record data back
     *
     * @param array $data Initial data to save
     * 
     * @return boolean Operation success
     */
    public function sync($data = null)
    {
        $this->insertToAbraFlexi($data);
        $insertResult = $this->lastResponseCode;
        if ($insertResult == 201) {
            $this->reload();
        }
        $loadResult = $this->lastResponseCode;
        return $this->dryRun ? $insertResult == 200 : ($insertResult + $loadResult) == 401;
    }
```

**Comment by Pepino483** [comment]
Za mě to vypadá v pořádku.
