### ISSUE TITLE
Chyba filtrování s gt

### ISSUE THREAD

**Issue by vojtasvoboda** [Spoje-NET/php-abraflexi#35]
Od 5.12. mi přestalo fungovat filtrování:

```
$response = $invoices->getColumnsFromFlexiBee($columns, [
        'id' => "gt $lastInvoiceId",
        'storno' => false,
        'limit' => 100,
]);
```

které pak [generuje URL](https://github.com/Spoje-NET/php-abraflexi/blob/main/src/AbraFlexi/RO.php#L2098) ve tvaru:

`/faktura-vydana/?(id%20gt%20%2789587%27and%20storno%20eq%20false)&limit=100`

Dle podpory je problém v konstrukci `id gt '89587'` a správně to má být `id gt 89587`, což dává smysl a doopravdy při manuální změně v URL to funguje. Nicméně v rámci https://www.flexibee.eu/k/prehled-verzi-flexibee/prehled-verzi-abra-flexi-2023/ jsem zmínku o této změně nedohledal, asi to nebrali jako breaking change :-)

Jako hot fix jsem použil:

```
$response = $invoices->getColumnsFromFlexiBee($columns, [
        0 => "id gt $lastInvoiceId",
        'storno' => false,
        'limit' => 100,
]);
```

Ale mělo by to být ošetřeno na úrovni knihovny nejspíš.

**Comment by Vitexus** [comment]
@vojtasvoboda čuji podraz tady: https://github.com/Spoje-NET/php-abraflexi/blob/0470ae0342432c1eb701856d80b8be2343b91868/src/AbraFlexi/Functions.php#L199

**Comment by Vitexus** [comment]
Jářku, @vojtasvoboda prosím Vás už to bude nějakej ten rok co jsem to přejmenoval z 

:warning: _getColumnsFromFlexiBee_ na **getColumnsFromAbraFlexi** :warning: 

```
PHP Fatal error:  Uncaught Error: Call to undefined method AbraFlexi\FakturaVydana::getColumnsFromFlexiBee() in /home/vitex/Projects/EASE/php-spojenet-abraflexi/Examples/Filtering.php:26
```
#JenomUpozorňuju

**Comment by vojtasvoboda** [comment]
Já bohužel jedu ještě na spoje.net/flexipeehp:1.6.10, ale právě se chystám na postupný update :-)

**Comment by Vitexus** [comment]
> Já bohužel jedu ještě na spoje.net/flexipeehp:1.6.10, ale právě se chystám na postupný update :-)

Chápu: když něco funguje taxe f tom nehrab ... 

Tak to jsem zvědav jak to pujde. Za ty +-3roky je tam navíc pár tisíc commitů. 

Poslední dobou hodně používám phpstan, takže v samotnté flexibee knihovně se snížil počet breberek z několika set na teď asi cca 30. + se snažím alespoň trochu řešit unit testy a ty taky sem tam nejaky ten problem ukazou.
