### ISSUE TITLE
Attachments upload not working

### ISSUE THREAD

**Issue by petaak** [Spoje-NET/php-abraflexi#40]
Attachments upload does not work after updating to the latest dev-main version. After some research I think it is caused by this commit https://github.com/Spoje-NET/php-abraflexi/commit/ab6b9e6d66ffea41e5a61d1eb32869a7ddc74e7f. Previous revision (https://github.com/Spoje-NET/php-abraflexi/commit/85f48f414ebe359671593b26023960a723e1b5cf) works fine.

My code:
```php
$connectionOptions = [
            'company' => $this->companyName,
            'url' => $this->serverUrl,
            'user' => $this->username,
            'password' => $this->password,
        ];
$invoiceId = 1234;
$fakturaPrijata = new FakturaPrijata($invoiceId, $connectionOptions);
$priloha = Priloha::addAttachment($fakturaPrijata, 'attachment.txt', 'Attachment content', 'text/plain');
```
The response HTTP code is 401 and the body says "Authorization required":
```
{"winstrom":{"@version":"1.0","success":"false","message":"Authorization required"}}
```

**Comment by petaak** [comment]
There is no username and password in the Authorization HTTP header of the request. The header looks like this:
```
Authorization: Basic Og==
```
Only the colon is encoded in the base64 string.

**Comment by Vitexus** [comment]
@petaak please confirm functionality

**Comment by petaak** [comment]
It works, thanks for the quick fix.
