### ISSUE TITLE
 Type of AbraFlexi\Zavazek::$evidence must be ?string (as in class AbraFlexi\RO)

### ISSUE THREAD

**Issue by jaroslavlibal** [Spoje-NET/php-abraflexi#51]
https://github.com/Spoje-NET/php-abraflexi/blob/0e578c4280e1dfd15982a2c1cb84fcadddc180f8/src/AbraFlexi/Zavazek.php#L27

**Comment by Vitexus** [comment]
@jaroslavlibal Do you need release ?

**Comment by jaroslavlibal** [comment]
Not really, we'll use a specific commit. Thanks!
